CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(50),
	EMAIL CHARACTER VARYING(50) NOT NULL,
	LOGIN CHARACTER VARYING(50) NOT NULL,
	BIRTHDAY DATE NOT NULL
);
ALTER TABLE PUBLIC.USERS ADD CONSTRAINT IF NOT EXISTS USER_PK PRIMARY KEY (ID);
CREATE TABLE IF NOT EXISTS PUBLIC.FILM (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(100) NOT NULL,
	DESCRIPTION CHARACTER VARYING(1000) NOT NULL,
	REALEASE_DATE DATE NOT NULL,
	DURATION INTEGER NOT NULL,
	RATING_ID INTEGER NOT NULL,
	CONSTRAINT FILM_PK PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS PUBLIC.RATING (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(1000) NOT NULL
);
ALTER TABLE PUBLIC.RATING ADD CONSTRAINT IF NOT EXISTS RATING_PK PRIMARY KEY (ID);
CREATE TABLE IF NOT EXISTS PUBLIC.LIKES (
	USER_ID INTEGER NOT NULL,
	FILM_ID INTEGER NOT NULL,
	CONSTRAINT NEWTABLE_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(ID),
	CONSTRAINT NEWTABLE_FK_1 FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILM(ID)
);
CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDS (
	USER_ID INTEGER NOT NULL,
	FRIEND_ID INTEGER NOT NULL,
	STATUS CHARACTER VARYING NOT NULL,
	CONSTRAINT FRIENDS_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(ID),
	CONSTRAINT FRIENDS_FK_1 FOREIGN KEY (FRIEND_ID) REFERENCES PUBLIC.USERS(ID)
);
CREATE TABLE IF NOT EXISTS PUBLIC.GENRE (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(1000) NOT NULL,
	CONSTRAINT GENRE_PK PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS PUBLIC.FILMS_GENRES (
	FILM_ID INTEGER NOT NULL,
	GENRE_ID INTEGER NOT NULL,
	CONSTRAINT FILMS_GENRES_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILM(ID),
	CONSTRAINT FILMS_GENRES_FK_1 FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC.GENRE(ID)
);